#!/usr/bin/env node
/**
 * scrape-maps.mjs  — local browser automation (Playwright)
 *
 * Opens Google Maps in a real Chromium on YOUR machine, searches each place
 * from prototype/data.js, grabs its real photo + price (+ rating/reviews if
 * found), downloads the photo, and writes an overlay the app merges on top of
 * the placeholder data.
 *
 * Outputs:
 *   ../prototype/images/<id>.jpg     (downloaded photos)
 *   ../prototype/place-media.js      (window.PLACE_MEDIA overlay; merged by data.js)
 *
 * ⚠️  Automating Google Maps is against Google's ToS. Use on your own machine,
 *     for your own prototype, gently. Selectors may break when Google changes
 *     its HTML — re-check the evaluate() block if extraction stops working.
 *
 * Uses your installed Google Chrome (Playwright channel: "chrome") — no
 * Chromium download needed. Requires Node.js 18+ (Playwright needs it).
 *
 * Setup (one time):
 *   cd scripts
 *   npm install
 *
 * Run:
 *   node scrape-maps.mjs                 # visible browser, all places, resumes
 *   node scrape-maps.mjs --headless
 *   node scrape-maps.mjs --limit 5       # test on first 5
 *   node scrape-maps.mjs --start 40 --limit 20
 *   node scrape-maps.mjs --only cafe     # one category
 *   node scrape-maps.mjs --force         # re-scrape even if already done
 */

import { chromium } from "playwright";
import { readFileSync, writeFileSync, existsSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const PROTO = resolve(__dirname, "../prototype");
const IMG_DIR = resolve(PROTO, "images");
const MEDIA_JS = resolve(PROTO, "place-media.js");

function getArg(name, fb) {
  const i = process.argv.indexOf(`--${name}`);
  if (i === -1) return fb;
  const n = process.argv[i + 1];
  return n && !n.startsWith("--") ? n : true;
}
const HEADLESS = !!getArg("headless", false);
const KEEP_PHOTOS = !!getArg("keep-photos", false); // refresh metadata, don't re-download existing photos
const REVIEWS = !!getArg("reviews", false);          // also grab latest ~10 reviews per place
const MISSING_COORDS = !!getArg("missing-coords", false); // only (re)process places lacking real coords
const LIMIT = Number(getArg("limit", "0")) || 0;
const START = Number(getArg("start", "0")) || 0;
const ONLY = getArg("only", "");
const FORCE = !!getArg("force", false);

const sleep = (ms) => new Promise((r) => setTimeout(r, ms));
const rand = (a, b) => a + Math.random() * (b - a);

// Places whose name+"Đà Lạt" search resolves to the wrong listing — use a precise query.
const QUERY_OVERRIDES = {
  "may-lang-thang-82": "Mây Lang Thang Phố Bên Đồi Đà Lạt",
};

/* ---------- load places from the prototype data ---------- */
function loadPlaces() {
  const win = {};
  const extra = resolve(PROTO, "places-extra.js");
  if (existsSync(extra)) new Function("window", readFileSync(extra, "utf8"))(win);
  new Function("window", readFileSync(resolve(PROTO, "data.js"), "utf8"))(win);
  return win.PLACES;
}

/* ---------- load existing overlay (for resume) ---------- */
function loadMedia() {
  if (!existsSync(MEDIA_JS)) return {};
  try {
    const win = {};
    new Function("window", readFileSync(MEDIA_JS, "utf8"))(win);
    return win.PLACE_MEDIA || {};
  } catch { return {}; }
}
function saveMedia(media) {
  writeFileSync(MEDIA_JS,
    "/* Auto-generated by scripts/scrape-maps.mjs — real Google Maps photos/prices.\n" +
    "   Merged on top of data.js by id. Safe to delete/regenerate. */\n" +
    "window.PLACE_MEDIA = " + JSON.stringify(media, null, 2) + ";\n", "utf8");
}

/* ---------- accept Google's consent screen if shown ---------- */
async function handleConsent(page) {
  for (const sel of [
    'button[aria-label="Accept all"]', 'button[aria-label="Reject all"]',
    'button[aria-label="Chấp nhận tất cả"]', 'button[aria-label="Từ chối tất cả"]',
  ]) {
    const b = await page.$(sel);
    if (b) { await b.click().catch(() => {}); await sleep(1200); return; }
  }
  const t = page.locator('button:has-text("Accept all"), button:has-text("Chấp nhận"), button:has-text("Reject all")').first();
  if (await t.count().catch(() => 0)) { await t.click().catch(() => {}); await sleep(1200); }
}

/* ---------- extract photo url + price + rating from the place panel ---------- */
async function extract(page) {
  // scroll the place panel so more photos lazy-load
  await page.evaluate(() => {
    const panel = document.querySelector('div[role="main"]');
    if (panel) panel.scrollBy(0, 700);
  }).catch(() => {});
  await sleep(900);
  return page.evaluate(() => {
    const out = {};
    const seen = new Set();
    const imgs = [];
    for (const i of document.querySelectorAll("img")) {
      let s = i.src;
      if (!s || !s.includes("googleusercontent.com")) continue;
      if (s.includes("=w16") || s.includes("=s16") || s.includes("/a/") || s.includes("=w86")) continue; // skip icons/avatars
      const key = s.split("=")[0];
      if (seen.has(key)) continue;
      seen.add(key);
      imgs.push(s);
      if (imgs.length >= 6) break;
    }
    out.imgs = imgs;
    out.img = imgs[0] || null;

    const rn = document.querySelector("div.F7nice");
    if (rn) {
      const txt = rn.innerText || "";
      const r = txt.match(/([0-9]+[.,][0-9])/);
      if (r) out.rating = parseFloat(r[1].replace(",", "."));
      const rv = txt.match(/\(([\d.,\s]+)\)/);
      if (rv) out.reviews = parseInt(rv[1].replace(/[.,\s]/g, ""), 10);
    }

    let priceText = null;
    for (const s of document.querySelectorAll("span, div")) {
      const t = (s.textContent || "").trim();
      if (/^[₫]{1,4}$/.test(t) || /^[$]{1,4}$/.test(t)) { priceText = t; break; }
    }
    if (!priceText) {
      const m = (document.body.innerText || "").match(/[₫]{1,4}(?![\d])/);
      if (m) priceText = m[0];
    }
    out.priceText = priceText;

    let phone = null;
    const pb = document.querySelector('button[data-item-id^="phone:tel:"]');
    if (pb) phone = pb.getAttribute("data-item-id").replace("phone:tel:", "");
    if (!phone) {
      const a = document.querySelector('button[aria-label^="Phone:"], button[aria-label^="Điện thoại:"]');
      if (a) phone = a.getAttribute("aria-label").replace(/^[^:]+:\s*/, "").trim();
    }
    out.phone = phone;
    return out;
  });
}

// open the reviews tab, sort by newest, scroll, and grab up to 10 reviews
async function extractReviews(page) {
  try {
    const tab = page.locator('button[role="tab"]:has-text("Bài đánh giá"), button:has-text("Bài đánh giá"), button[role="tab"]:has-text("Reviews")').first();
    if (await tab.count().catch(() => 0)) { await tab.click().catch(() => {}); await sleep(1800); }
  } catch (e) {}
  try {
    const sortBtn = page.locator('button[aria-label^="Sắp xếp"], button[aria-label*="Sort reviews"], button[data-value="Sort"]').first();
    if (await sortBtn.count().catch(() => 0)) {
      await sortBtn.click().catch(() => {}); await sleep(700);
      const newest = page.locator('[role="menuitemradio"]:has-text("Mới nhất"), [role="menuitem"]:has-text("Mới nhất"), [role="menuitemradio"]:has-text("Newest")').first();
      if (await newest.count().catch(() => 0)) { await newest.click().catch(() => {}); await sleep(1600); }
    }
  } catch (e) {}
  for (let i = 0; i < 6; i++) {
    await page.evaluate(() => {
      const els = document.querySelectorAll("div[data-review-id]");
      const last = els[els.length - 1];
      const sc = (last && last.closest('div[tabindex="-1"]')) || document.querySelector('div[role="main"]');
      if (sc) sc.scrollBy(0, 1600);
    }).catch(() => {});
    await sleep(800);
    const n = await page.$$eval("div[data-review-id]", (a) => a.length).catch(() => 0);
    if (n >= 12) break;
  }
  return page.$$eval("div[data-review-id]", (nodes) => {
    const out = []; const seen = new Set();
    for (const n of [...nodes]) {
      if (out.length >= 10) break;
      const author = (n.querySelector(".d4r55")?.textContent || "Khách").trim();
      let rating = 0;
      const rEl = n.querySelector('[aria-label*="sao"], [aria-label*="star"]');
      if (rEl) { const m = (rEl.getAttribute("aria-label") || "").match(/(\d)/); if (m) rating = +m[1]; }
      const text = (n.querySelector(".wiI7pd")?.textContent || n.querySelector(".MyEned")?.textContent || "").trim();
      const when = (n.querySelector(".rsqaWe")?.textContent || "").trim();
      const key = author + "|" + text.slice(0, 40);
      if (seen.has(key)) continue;
      seen.add(key);
      if (text || rating) out.push({ author, rating, text, when });
    }
    return out;
  }).catch(() => []);
}

function priceLevel(text) {
  if (!text) return "";
  const m = text.match(/[₫$]/g);
  return m ? Math.min(m.length, 3) : "";
}
function upsizeImg(url) {
  if (!url) return url;
  return url.replace(/=w\d+-h\d+[^?]*$/, "=w800-h600-k-no");
}

async function downloadImage(context, url, dest) {
  const res = await context.request.get(url, { timeout: 30000 });
  if (!res.ok()) throw new Error("img HTTP " + res.status());
  writeFileSync(dest, Buffer.from(await res.body()));
}

async function main() {
  if (!existsSync(IMG_DIR)) mkdirSync(IMG_DIR, { recursive: true });

  let places = loadPlaces();
  if (ONLY) places = places.filter((p) => p.category === ONLY);
  places = places.slice(START, LIMIT ? START + LIMIT : undefined);

  const media = loadMedia();
  // Use the user's installed Google Chrome (not bundled Chromium).
  const browser = await chromium.launch({ headless: HEADLESS, channel: "chrome", slowMo: 40 });
  const context = await browser.newContext({
    viewport: { width: 1280, height: 900 },
    locale: "vi-VN",
    userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0 Safari/537.36",
  });
  const page = await context.newPage();

  let ok = 0, skip = 0, fail = 0, consentDone = false;

  for (const place of places) {
    const imgPath = resolve(IMG_DIR, place.id + ".jpg");
    if (MISSING_COORDS) {
      if (media[place.id] && media[place.id].lat != null) { skip++; continue; }
    } else if (!FORCE && media[place.id] && media[place.id].img && existsSync(imgPath)) {
      console.log(`= skip (done): ${place.name}`); skip++; continue;
    }
    try {
      const q = encodeURIComponent(QUERY_OVERRIDES[place.id] || (place.name + " Đà Lạt"));
      await page.goto(`https://www.google.com/maps/search/${q}`, { waitUntil: "domcontentloaded", timeout: 60000 });
      if (!consentDone) { await handleConsent(page); consentDone = true; }
      await sleep(rand(2500, 3800));

      // if a results list shows, open the first result
      const first = await page.$("a.hfpxzc");
      if (first) { await first.click().catch(() => {}); await sleep(rand(2500, 3500)); }

      await page.waitForSelector('img[src*="googleusercontent.com"]', { timeout: 12000 }).catch(() => {});
      const data = await extract(page);

      const rec = media[place.id] || {};
      // real coordinates from the resolved place URL (!3d<lat>!4d<lng>) — wait for it to settle
      await page.waitForFunction(() => /!3d-?\d+\.\d+!4d-?\d+\.\d+/.test(location.href), { timeout: 5000 }).catch(() => {});
      const cm = page.url().match(/!3d(-?\d+\.\d+)!4d(-?\d+\.\d+)/);
      if (cm) {
        const la = parseFloat(cm[1]), ln = parseFloat(cm[2]);
        // only accept coords inside Lâm Đồng (reject same-named places in HCMC etc.)
        if (la >= 11.5 && la <= 12.3 && ln >= 108.0 && ln <= 108.95) { rec.lat = la; rec.lng = ln; }
      }
      if (KEEP_PHOTOS && rec.photos && rec.photos.length) {
        // keep already-downloaded photos; only refresh metadata (phone/price/rating)
      } else {
        const photos = [];
        const toGrab = (data.imgs || []).slice(0, 4);
        for (let k = 0; k < toGrab.length; k++) {
          const fname = k === 0 ? place.id + ".jpg" : place.id + "-" + (k + 1) + ".jpg";
          try {
            await downloadImage(context, upsizeImg(toGrab[k]), resolve(IMG_DIR, fname));
            photos.push("images/" + fname);
          } catch (e) { /* skip this photo */ }
        }
        if (photos.length) { rec.img = photos[0]; rec.photos = photos; }
      }
      const lvl = priceLevel(data.priceText);
      if (lvl !== "") rec.price = lvl;
      if (data.phone) rec.phone = data.phone;
      if (data.rating) rec.rating = data.rating;
      if (data.reviews) rec.reviews = data.reviews;
      if (REVIEWS) {
        const revs = await extractReviews(page);
        if (revs && revs.length) rec.comments = revs;
      }
      rec.source = "google-maps";

      media[place.id] = rec;
      saveMedia(media); // incremental save = resumable
      console.log(`+ ${place.name} -> ${rec.photos ? rec.photos.length : 0}📷 ${rec.phone ? "☎" : ""} ${rec.comments ? rec.comments.length + "💬" : ""} ${rec.rating ? rec.rating + "★" : ""}`);
      ok++;
    } catch (err) {
      console.error(`x ${place.name}: ${err.message}`);
      await page.screenshot({ path: resolve(IMG_DIR, "_debug_" + place.id + ".png") }).catch(() => {});
      fail++;
    }
    await sleep(rand(1500, 3000)); // be gentle
  }

  await browser.close();
  console.log(`\nDone. ok=${ok} skip=${skip} fail=${fail}`);
  console.log(`Photos -> ${IMG_DIR}`);
  console.log(`Overlay -> ${MEDIA_JS} (reload the prototype to see real photos/prices)`);
}

main().catch((e) => { console.error(e); process.exit(1); });
